from sklearn.cluster import KMeans
import numpy as np

from app.services.cluster_naming import generate_cluster_name

def group_documents(documents, n_clusters=3):

    if len(documents) == 0:
        return {}

    if len(documents) < n_clusters:
        n_clusters = len(documents)

    embeddings = []

    for doc in documents:
        embeddings.append(doc["document_embedding"]) # every document has various fields, index, filename, metadata, embeddings.

    embeddings = np.array(embeddings)

    kmeans = KMeans(
        n_clusters=n_clusters,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(embeddings) # This will give labels = [0, 1, 1, 2, 0]

    clusters = {}

    for label, doc in zip(labels, documents):

         cluster_name = f"Cluster {label}"

         if cluster_name not in clusters:
            clusters[cluster_name] = []

         clusters[cluster_name].append(doc["filename"]) # {"Cluster 1":["resume.pdf"]} if next file is cluster 1 then it is added inside cluster 1.
# inside clusters it has cluster 0 and the filenames belonging to that clusters. filenames are appended.

    # Renaming each cluster using Gemini
    named_groups = {}

    for cluster, files in clusters.items():
# for set of files inside one cluster inside clusters. Cluster 0 : ["resume.pdf", "Sushanth_M_S_Resume.pdf"]
        name = generate_cluster_name(files)
# names is generated by seeing all the filenames of the files inside each Cluster
        named_groups[name] = files

    return named_groups